---
#
# Install/run nginx
#

- name: Check/Install EPEL Repo for nginx
  yum: name={{epel_repo}}
      state=present
  become: true

- name: Add nginx repo
  template:
    src=yum.repo
    dest=/etc/yum.repos.d/nginx.repo
    owner=root
    group=root
    mode=0644
  become: true

- name: Install nginx, httpd-tools, httplib2
  yum: name={{ item }} state=present
  become: true
  with_items:
    - nginx
    - httpd-tools
    - python-httplib2

# create /etc/nginx/conf.d/ directory
- name: Create nginx directory structure
  file: path=/etc/nginx/conf.d/
    state=directory
    mode=0755
  become: true

# deploy kibana.conf with FQDN
- name: Setup nginx reverse proxy for kibana
  template:
    src=kibana.conf.j2
    dest=/etc/nginx/conf.d/kibana.conf
    owner=root
    group=root
    mode=0644
  become: true
  register: nginx_needs_restart

# deploy basic nginx.conf 8080 vhost
- name: Setup nginx TCP/8080 vhost for SSL certificate
  template:
    src=nginx.conf.j2
    dest=/etc/nginx/nginx.conf
    owner=root
    group=root
    mode=0644
  become: true

- name: Fix nginx init.d script pidfile location
  lineinfile:
    path=/etc/sysconfig/nginx
    regexp='^PIDFILE=.*$'
    line='PIDFILE=/run/nginx.pid'

# start nginx service
- name: Start nginx service
  service:
    name: nginx
    state: restarted
    enabled: true
  ignore_errors: true
  when: nginx_needs_restart != 0
  become: true

- name: Set nginx to start on boot
  command: systemctl enable nginx.service
  ignore_errors: true
  become: true

# we only want to enable EPEL for some packages
- name: Remove EPEL Repo
  yum: name={{epel_repo}}
      state=absent
  become: true
